### ISSUE TITLE
Add syslog support

### ISSUE THREAD

**Issue by graste** [berlinonline/converjon#105]
Supporting the syslog as a log option means more flexibility for devops/administrators when using `converjon`.

**Comment by lnwdr** [comment]
Syslog implementations for node all depend on native extensions so they require build-tools for deployment.

I'm not sure, if we should add that dependency.

**Comment by aeytom** [comment]
There is no need for native syslog support on a systemd/journald environment. Output to stderr/stdout apears in journal.
