### ISSUE TITLE
Version 2.5.0 new "file"-feature with timeouts

### ISSUE THREAD

**Issue by neffets** [berlinonline/converjon#109]
Hello, I am using http-access and new file-access-feature of converjon.

1) Version 2.4.2 locally installed in a fresh directory:
> stg:/tmp/c242 # /usr/bin/node node_modules/.bin/converjon --config /etc/converjon/current.yml --config /etc/converjon/alias-img.yml --debug stdout

all ok. Images are rendered. Debug-Infos are scolling

2) Version 2.5.0 locally installed in a fresh directory
> stg:/tmp/c250 # /usr/bin/node node_modules/.bin/converjon --config /etc/converjon/current.yml --config /etc/converjon/alias-img.yml --debug stdout

No images are rendered for file-alias.
For /status and for url-requests debug-log shows infos. For file-alias-requests there is no debug-info at all.

Here for information the verbose install-tree for both versions:

* c242 Installation

npm WARN engine converjon@2.4.2: wanted: {"node":">=0.10.7 <0.11.0"} (current: {"node":"0.12.4","npm":"2.10.1"})
converjon@2.4.2 node_modules/converjon
├── calmcard@0.1.1
├── clone@0.1.19
├── moniker@0.1.2
├── minimist@1.1.1
├── mkdirp@0.5.1 (minimist@0.0.8)
├── send@0.9.3 (destroy@1.0.3, ms@0.6.2, fresh@0.2.4, escape-html@1.0.1, range-parser@1.0.2, depd@0.4.5, debug@2.0.0, mime@1.2.11, on-finished@2.1.0, etag@1.4.0)
├── rsvp@3.0.18
├── request@2.57.0 (caseless@0.10.0, aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, tunnel-agent@0.4.0, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, node-uuid@1.4.3, qs@3.1.0, combined-stream@1.0.3, bl@0.9.4, mime-types@2.0.13, form-data@0.2.0, http-signature@0.11.0, tough-cookie@1.2.0, hawk@2.3.1, har-validator@1.7.1)
├── nodeunit@0.9.1 (tap@0.7.1)
├── cjson@0.3.1 (jsonlint@1.6.0)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── js-yaml@3.3.1 (esprima@2.2.0, argparse@1.0.2)
└── cli-color@0.3.3 (d@0.1.1, timers-ext@0.1.0, memoizee@0.3.8, es5-ext@0.10.7)

* c250 installation

npm WARN engine converjon@2.5.0: wanted: {"node":">=0.10.7 <0.11.0"} (current: {"node":"0.12.4","npm":"2.10.1"})
converjon@2.5.0 node_modules/converjon
├── calmcard@0.1.1
├── clone@0.1.19
├── moniker@0.1.2
├── minimist@1.1.1
├── send@0.9.3 (destroy@1.0.3, ms@0.6.2, fresh@0.2.4, escape-html@1.0.1, range-parser@1.0.2, depd@0.4.5, debug@2.0.0, mime@1.2.11, on-finished@2.1.0, etag@1.4.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── rsvp@3.0.18
├── request@2.57.0 (caseless@0.10.0, aws-sign2@0.5.0, forever-agent@0.6.1, stringstream@0.0.4, tunnel-agent@0.4.0, oauth-sign@0.8.0, isstream@0.1.2, json-stringify-safe@5.0.1, node-uuid@1.4.3, qs@3.1.0, combined-stream@1.0.3, bl@0.9.4, mime-types@2.0.13, form-data@0.2.0, http-signature@0.11.0, tough-cookie@1.2.0, hawk@2.3.1, har-validator@1.7.1)
├── nodeunit@0.9.1 (tap@0.7.1)
├── cjson@0.3.1 (jsonlint@1.6.0)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
├── js-yaml@3.3.1 (esprima@2.2.0, argparse@1.0.2)
└── cli-color@0.3.3 (d@0.1.1, timers-ext@0.1.0, memoizee@0.3.8, es5-ext@0.10.7)

Error could be in file node_modules/converjon/lib/source.js around line 204
if "copy_source_file" return copy_source(item);; else return /* NOTHING */

Should the else-case return something?

**Comment by neffets** [comment]
I can now use the 2.5.0 version too.
"file" Alias Feature is working IF (and only if) the "fallback_base_file_paths" config option IS SET

fallback_base_file_paths:
  - "/var/www/imperia9-live/htdocs"

If "fallback_base_file_paths" is missing, then all requests will fail.

(works with ok-images and also with error-path-images)

(ticket #110 remains, the url feature is not working for me. Also not if I install ist via: npm install converjon@2.5.0 --no-shrinkwrap)

**Comment by paulrobertlloyd** [comment]
Seeing this also (`?file` path not working, unless I set a value for `fallback_base_file_paths:`).
