### ISSUE TITLE
Version 2.5.0 unknown-urls with timeout

### ISSUE THREAD

**Issue by neffets** [berlinonline/converjon#110]
> curl -o /dev/null 'http://localhost:8000/?ts=1378670706&height=280&width=780&url=http%3A%2F%2Flocalhost%2Ftest%2F_assets%2Funknown.jpg'

Same problem as in issue #109 with parameter url.
But now only for un-accessable ressources.
- Try loading an unknown ressource.

```
::ffff:127.0.0.1 "GET /status HTTP 1.1" 200 1964
[DEBUG] 12 Locked: source file
[DEBUG] 12 Locked: metadata
[DEBUG] 12 Locked: target file
[DEBUG] 12 Metadata is stale
[DEBUG] 12 Requesting download 
[DEBUG] 12 Starting request http://localhost/test/_assets/unknown.jpg
[DEBUG] 12 Received invalid response
[DEBUG] 12 Download failed
[DEBUG] 12 Released lock: metadata
[DEBUG] 12 Released lock: source file
[DEBUG] 12 Released lock: target file
::ffff:127.0.0.1 "GET /status HTTP 1.1" 200 1964
```

The debug-Log scrolls immediately and says "Download failed".
But the request is not ending, the curl receives no response at all and is hanging till 30seconds-timeout.

Problem:
- no response
- no header lines
- not closing the connection

**Comment by lnwdr** [comment]
should also be solved alone with #109

**Comment by lnwdr** [comment]
Is this still an issue?

**Comment by neffets** [comment]
no, version 2.7.2. was stable on live and on dev-boxes.
