### ISSUE TITLE
Source HTTP header whitelist not working

### ISSUE THREAD

**Issue by graste** [berlinonline/converjon#128]
Are the brackets correct in here? https://github.com/berlinonline/converjon/blob/master/lib/server.js#L60

**Comment by graste** [comment]
Fixed in https://github.com/berlinonline/converjon/commit/da7f10423eb8e2315687c1ba90644c997ad189db by @aeytom

**Comment by graste** [comment]
@lnwdr Release this as ```2.7.1```  or even ```3.0.0``` as the (buggy) default behaviour changes?

**Comment by lnwdr** [comment]
Since this fixes a mismatch between documentation and actual result and the documentation remains unchanged, it's a patch version bump. So `2.7.2` is fine.

**Comment by lnwdr** [comment]
But please don't commit/push directly to `master` as stated here: https://github.com/berlinonline/converjon/blob/master/CONTRIBUTING.md
