### ISSUE TITLE
Converjon fails on Node v6 w/ "options.hasOwnProperty is not a function"

### ISSUE THREAD

**Issue by graste** [berlinonline/converjon#133]
After installing a newer nodejs version converjon stopped working. Error is `options.hasOwnProperty is not a function`. Excerpt form the debug/error log:

```
[DEBUG] 2 Target file doesn't exist. Must be regenerated.
[DEBUG] 2 Applying cropping and constriants
[DEBUG] 2 Released lock: metadata
[DEBUG] 2 Released lock: source file
[DEBUG] 2 Released lock: target file
[ERROR] options.hasOwnProperty is not a function
```

When it works the debug log looks more like this:

```
[DEBUG] 0 Target file doesn't exist. Must be regenerated.
[DEBUG] 0 Applying cropping and constriants
[DEBUG] 0 Requesting image conversion
[DEBUG] 0 Image conversion successful
[DEBUG] 0 Released lock: metadata
[DEBUG] 0 Released lock: source file
[DEBUG] 0 Releasing lock: target file
```

I checked different node/npm versions w/ converjon 2.7.2:
- node v6.2.1 w/ npm 3.9.3: fails (`--no-shrinkwrap` fails as well)
- node v5.9.1 w/ npm 3.7.3: works
- node v4.4.5 w/ npm: 2.15.5: works

The tests are running without errors on the node v6 version. I did not investigate further, but think `hasOwnProperty` and other functions have been deprecated in V8 and have since been removed in version 6.

**Comment by graste** [comment]
What's your take at this @lnwdr?

**Comment by lnwdr** [comment]
Node 6 has issues with a lot of JS libs and tools at the moment.

For now, i'd say: stick with the 4.x.x LTS version of node since it's the recommended one anyway.
