### ISSUE TITLE
default.yml overwrites options from urls-defined-yml

### ISSUE THREAD

**Issue by neffets** [berlinonline/converjon#134]
If the special yml (e.g. akzente.yml) with proper defined urls-section comes first and the default yml (without onw urls-section) (e.g. bo.yml) comes later:
Then all options from special yml are overwritten.

Test it:
* akzente.yml with constraints -> width -> max 1440
* bo.yml with constraints -> width -> max 1000
Then request image fpr special akzente with width 1440: you will get error "violated constraint width:1000"

**Comment by lnwdr** [comment]
Which config values override which is determined by the order of the config files, not by the URLs that they match.

So, if a URL specific file defines an exception from the default file, it needs to be added after the default one:

```sh
conversion --config bo.yml --config akzente.yml
```

I just tested it and it is working as intended.

The documentation could be more explicit in this regard, though.

**Comment by neffets** [comment]
Yes,
but I are using the directory-option
>    /usr/bin/node /usr/bin/converjon --config-dir /etc/converjon/current
And the order of the ymls in the directory is not determinded.
Can You please add, that (at minimum), the file in the directory will be used in alphabetical order?
  Then I could name them as 00_..., 01_..., 99_...

Thanx

**Comment by lnwdr** [comment]
The files from a config directory should already be applied in the order they appear in that directory. In this case, that would mean that "akzente.yml" comes before "bo.yml" which would fit your initial issue description.

Please check if renaming the files with "01", "02", etc. prefixes helps. If not, we can add explicit sorting of the filenames.

**Comment by neffets** [comment]
Renaming helped. we now use 00_default_xyz for the default and 10_ 20_ for the others. This way it works as aspected.
Perhaps comment it in the documentation, that .yml-file-order is relevant.

**Comment by lnwdr** [comment]
It's already in the documentation.

> To load a directory containing one or more config file, use the --config-dir option. Config files will be   added in the order they appear in that directory.
