### ISSUE TITLE
Cache item timestamp should not use mtime

### ISSUE THREAD

**Issue by lnwdr** [berlinonline/converjon#136]
Changes introduced in version 2.7.3 related to issue #135 introduced a regression in creating cache item timestamps:

Using the original source file's time can result in cache item timestamp that are always far in the past. This leads to the cache item always being stale.

Revert to the previous method using the current time at the point of creation of the cache item.

**Comment by neffets** [comment]
Solved.

Thanx, the 2.7.4. works as expected.

**Comment by lnwdr** [comment]
@neffets Does that mean, we can close #135 as well?
