### ISSUE TITLE
Option to strip meta data from output images

### ISSUE THREAD

**Issue by graste** [berlinonline/converjon#67]
ImageMagick has the `-strip` parameter that we should support via a `strip` parameter as well.

As we don't know whether images contain color profile information simply stripping those meta data from the output image may lead to unexpected visual problems. Converting images using an ICC sRGB color profile might be the best solution.

As more and more parameters are added to converjon it might be nice to think about a parameter like `optimize` that takes values like `thumb` or `web` to automatically use parameters like `interlace=plane&strip_meta=yes&use_srgb=yes`.

Using an ICC color profile usually involves accepting a license etc. to be able to download and use it. It must be checked whether it can be bundled or if users of converjon have to download and provide a profile separately.

Example ICC sRGB profiles: http://www.color.org/srgbprofiles.xalter

**Comment by lnwdr** [comment]
A parameter like `strip_metadata` or something like that is a good idea.

> As more and more parameters are added to converjon it might be nice to think about a parameter like optimize that takes values like thumb or web to automatically use parameters like interlace=plane&strip_meta=yes&use_srgb=yes.

Basically, predefined presets of settings. Also nice. Will handle that in #70.
