### ISSUE TITLE
Adopt mozjpeg for better compression

### ISSUE THREAD

**Issue by kurtkraut** [berlinonline/converjon#69]
The Mozilla Foundation is investing time and resources in a more eficient JPEG encoder that is fully compatible with decoders in the wild. CloudFlare did a benchmark with an earlier release and [saw 3%](http://blog.cloudflare.com/experimenting-with-mozjpeg-2-0/) file size reduction, Mozilla states results up to 5%. This number has been improving on each mozjpeg release. There are many npm packages to manage this conversion (for instance, [mozjpeg](https://www.npmjs.com/package/mozjpeg)).

I'd like to suggest the adoption of mozjpeg for JPEGs as default but in the conf allow users to opt for ImageMagick

**Comment by lnwdr** [comment]
At this time, supporting other converter tools than ImageMagick is not planned. While the benefit of reduced size is nice, I don't think it's worth introducing an additional dependency and complexity right now. At the moment, the focus is more on fixing bugs and adding features.

This might be relevant for a future, more performance oriented release, though.
