### ISSUE TITLE
Use mash/node-imagemagick-native instead of CLI?

### ISSUE THREAD

**Issue by selfawaresoup** [berlinonline/converjon#71]
Instead of using CLI calls to run imagemagick, maybe use [mash/node-imagemagick-native](https://github.com/mash/node-imagemagick-native).

Avoiding CLI could greatly reduce complexity and potential errors. This needs to be evaluated.

**Comment by trendfischer** [comment]
The following diskussion might be helpful: https://github.com/mash/node-imagemagick-native/issues/46

But in theory, the native client should be much faster and on bigger files, it should have the same performance like the CLI.

**Comment by lnwdr** [comment]
[mash/node-imagemagick-native](https://github.com/mash/node-imagemagick-native) does not support cropping parameters, yet. There is an issue for that, though: https://github.com/mash/node-imagemagick-native/issues/52

**Comment by lnwdr** [comment]
Since converjon is probably mostly used to scale big source images down to thumbnails or web gallery versions, is should profit more from the performance characteristics of imagemagick (CLI).

Closing this issue for now.

**Comment by lnwdr** [comment]
New info on this: <https://github.com/mash/node-imagemagick-native/issues/46#issuecomment-55696841>

**Comment by lnwdr** [comment]
It also seems like node-imagemagick-native doesn't support cutting out specific parts of the source image. That is necessary for converjon's cropping.
