### ISSUE TITLE
converjon-cli is failing silently if input file doesn't exist

### ISSUE THREAD

**Issue by kurtkraut** [berlinonline/converjon#74]
I noticed if converjon-cli is requested to conver a non existant file it fails silently as I demonstrate below:

ktk@ktk8:/tmp/demo$ ls noexistantfile.jpg
ls: cannot access noexistantfile.jpg: No such file or directory
ktk@ktk8:/tmp/demo$ converjon-cli --help | head -n 1
converjon - 2.1.0
ktk@ktk8:/tmp/demo$ converjon-cli -w 200 -h 200 noexistantfile.jpg output.jpg
ktk@ktk8:/tmp/demo$ echo $?
0

**Comment by lnwdr** [comment]
Pushed a fix for this. Will go into the next release, very soon.
