### ISSUE TITLE
Provide an option to turn off cache

### ISSUE THREAD

**Issue by kurtkraut** [berlinonline/converjon#75]
It seems cache is mandatory for converjon 2.1.0. I'd like to be able to turn it off at config because I do have cache in another layer (ex.: nginx).

**Comment by lnwdr** [comment]
The cache layer should not interfere with other HTTP caching proxies since converjon obeys and passes along the relevant HTTP headers.

Are you having problems with the caching itself or do you just want prevent converjon from using disk space?

**Comment by lnwdr** [comment]
Is this still relevant or can I close it?

**Comment by kurtkraut** [comment]
Yes, this is still relevant and sorry for not replying earlier. In my case, I have an nginx handling requests before converjon and the web application itself. It caches the responses and serves it directly if the same URL was requested recently, both for the webapp, CSS, JS and for converted images by converjon.

Because caching is mandatory at the converjon level, I have two systems (nginx and converjon) storing the same images on each cache, taking up disk space unecessary. So this is why I see this feature as still relevant.

**Comment by DracoBlue** [comment]
:+1:

**Comment by lnwdr** [comment]
[Version 2.5.0](https://github.com/berlinonline/converjon/releases/tag/2.5.0) introduces a mechanism to automatically remove the cache items when the are no longer in use or no longer valid for caching: https://github.com/berlinonline/converjon/issues/19


[Here's the configuration for it.](https://github.com/berlinonline/converjon#garbage-collector)
