### ISSUE TITLE
Support getting source files from filesystem instead of URLs

### ISSUE THREAD

**Issue by graste** [berlinonline/converjon#91]
Currently `converjon` only supports getting source files for the transformations via URLs. It downloads the files prior to transforming it. For installations where `converjon` may be able to get the files via filesystem operations instead of via HTTP(s) it should be possible to shortcut the source file downloading. This may be because converjon and the source files are on the same host or because there's a mounted remote filesystem or the like.

I suggest adding a ```file=<relative_path>``` URL parameter that has priority over the ```url=<https://…>``` to enable `converjon` to get the file locally. A fallback to the `url` parameter may be a possible convenience variant when the local file is not available. I'm not decided on this.

Converjon needs a new setting for resolving the local files. I suggest something like ```download.file_base_path```. The relative file paths are added to this path to copy/transform from the source files.

**Comment by lnwdr** [comment]
There should be configurable aliases for local directories, similar to the URL-specific configurations.

Each one should have a `base_path` from which to load the images and a set of HTTP headers that should be sent on the responses.
