### ISSUE TITLE
Security measures and HTTP headers

### ISSUE THREAD

**Issue by graste** [berlinonline/converjon#98]
We should try to assert whether `converjon` is secure enough to command injection and checks URL parameters enough. I know we use `spawn` instead of `exec`, but does `convert` with certain cli arguments allow to execute arbitrary stuff?

Further on we should check whether some security related headers like CSP, no-sniff or similar can be sent to clients. Using some modules of [helmet](https://github.com/helmetjs/helmet) like [dont-sniff-mimetype](https://github.com/helmetjs/dont-sniff-mimetype) might be an option.

**Comment by lnwdr** [comment]
CLI injection is already a separate issue: #94

**Comment by lnwdr** [comment]
For now I only included the nosniff header.
